// ============================================
// AI VIDEO PIPELINE — After Effects Assembly Script
// Generated by Pipeline Workspace v7
// ============================================
// 
// INSTRUCTIONS:
// 1. Place your files in a project folder:
//    📂 project/
//    ├── 📂 shot/     ← shot_1.mp4, shot_2.mp4...
//    ├── 📂 voice/    ← voiceover.mp3 (or .wav)
//    ├── 📂 music/    ← music.mp3 (or .wav)
//    └── 📂 assets/   ← logo.png, etc.
//
// 2. Open After Effects
// 3. File → Scripts → Run Script File → select this .jsx
// 4. Select your project folder when prompted
// ============================================

(function(){
  // --- CONFIG ---
  var COMP_NAME = "Pipeline_Assembly";
  var COMP_W = 1920;
  var COMP_H = 1080;
  var COMP_FPS = 30;
  var COMP_DUR = 32; // +2s padding
  var TRANS_DUR = 0.5;
  var NUM_SHOTS = 6;
  
  // Shot durations from script (seconds)
  var shotDurs = [5,5,5,6,5,4];

  // On-screen text from script
  var shotTexts = ["—","—","\"PRE-MARKET ACCESS\" (Futura PT Light, mint accent)","\"WHALES MARKET\" (Helvetica Neue Light, royal purple gradient)","\"START TRADING PRE-MARKET NOW\" (Futura PT Medium, charcoal with mint underline)","\"WHALES.MARKET\" (Helvetica Neue Light, silver metallic finish)<br>\"Trade before everyone else\" (Futura PT Light, charcoal #2C2C2C, positioned 24px below logo baseline)"];

  // --- FOLDER PICKER ---
  var projFolder = Folder.selectDialog("Select your project folder (containing shot/, voice/, music/, assets/)");
  if(!projFolder){ alert("Cancelled."); return; }
  var shotFolder = new Folder(projFolder.fsName + "/shot");
  var voiceFolder = new Folder(projFolder.fsName + "/voice");
  var musicFolder = new Folder(projFolder.fsName + "/music");
  var assetsFolder = new Folder(projFolder.fsName + "/assets");

  // --- HELPERS ---
  function getFiles(folder, exts){
    if(!folder.exists) return [];
    var all = folder.getFiles();
    var filtered = [];
    for(var i=0;i<all.length;i++){
      var f = all[i];
      if(f instanceof File){
        var ext = f.name.split('.').pop().toLowerCase();
        for(var e=0;e<exts.length;e++){
          if(ext===exts[e]){filtered.push(f);break;}
        }
      }
    }
    // Sort by name
    filtered.sort(function(a,b){return a.name.localeCompare(b.name)});
    return filtered;
  }

  function importFile(f){
    var io = new ImportOptions(f);
    return app.project.importFile(io);
  }

  app.beginUndoGroup("Pipeline Assembly");

  // --- CREATE COMP ---
  var comp = app.project.items.addComp(COMP_NAME, COMP_W, COMP_H, 1, COMP_DUR, COMP_FPS);

  // --- IMPORT & PLACE SHOTS ---
  var shotFiles = getFiles(shotFolder, ["mp4","mov","avi","webm","mkv"]);
  var timeline = 0;

  // Create shot layers
  for(var i=0; i<Math.min(shotFiles.length, NUM_SHOTS); i++){
    var footage = importFile(shotFiles[i]);
    var layer = comp.layers.add(footage);
    layer.startTime = timeline;
    
    // Trim to script duration
    var dur = (i < shotDurs.length) ? shotDurs[i] : 4;
    layer.outPoint = timeline + dur;
    
    // Add cross dissolve (opacity fade) except first shot
    if(i > 0 && TRANS_DUR > 0){
      layer.opacity.setValueAtTime(timeline, 0);
      layer.opacity.setValueAtTime(timeline + TRANS_DUR, 100);
    }
    // Fade out at end except last shot
    if(i < Math.min(shotFiles.length, NUM_SHOTS) - 1 && TRANS_DUR > 0){
      layer.opacity.setValueAtTime(timeline + dur - TRANS_DUR, 100);
      layer.opacity.setValueAtTime(timeline + dur, 0);
    }
    
    // Scale to fit comp
    var sw = footage.width; var sh = footage.height;
    if(sw > 0 && sh > 0){
      var scaleX = (COMP_W / sw) * 100;
      var scaleY = (COMP_H / sh) * 100;
      var scale = Math.max(scaleX, scaleY);
      layer.transform.scale.setValue([scale, scale]);
    }
    
    layer.name = "Shot_" + (i+1);
    timeline += dur;
  }

  // --- IMPORT & PLACE VOICE-OVER ---
  var voFiles = getFiles(voiceFolder, ["mp3","wav","aac","m4a"]);
  if(voFiles.length > 0){
    var voFootage = importFile(voFiles[0]);
    var voLayer = comp.layers.add(voFootage);
    voLayer.startTime = 0;
    voLayer.name = "Voice_Over";
    voLayer.audioEnabled = true;
    // Move to bottom of layer stack
    voLayer.moveToEnd();
  }

  // --- IMPORT & PLACE MUSIC ---
  var muFiles = getFiles(musicFolder, ["mp3","wav","aac","m4a"]);
  if(muFiles.length > 0){
    var muFootage = importFile(muFiles[0]);
    var muLayer = comp.layers.add(muFootage);
    muLayer.startTime = 0;
    muLayer.name = "Music_BG";
    muLayer.audioEnabled = true;
    // Lower music volume (-12dB) so VO is clear
    muLayer.audio.audioLevels.setValue([-12, -12]);
    // Fade out music at end
    var fadeStart = Math.max(0, timeline - 2);
    muLayer.audio.audioLevels.setValueAtTime(fadeStart, [-12, -12]);
    muLayer.audio.audioLevels.setValueAtTime(timeline, [-48, -48]);
    muLayer.outPoint = timeline;
    muLayer.moveToEnd();
  }

  // --- ADD ON-SCREEN TEXT OVERLAYS ---
  var textTimeline = 0;
  for(var t=0; t<shotTexts.length; t++){
    var txt = shotTexts[t];
    if(txt && txt.length > 0 && txt !== "-" && txt !== "N/A" && txt !== "None"){
      var textLayer = comp.layers.addText(txt);
      textLayer.startTime = textTimeline;
      var dur2 = (t < shotDurs.length) ? shotDurs[t] : 4;
      textLayer.outPoint = textTimeline + dur2;
      textLayer.name = "Text_Shot_" + (t+1);
      
      // Style the text
      var textProp = textLayer.property("Source Text");
      var textDoc = textProp.value;
      textDoc.fontSize = 42;
      textDoc.fillColor = [1, 1, 1]; // white
      textDoc.strokeColor = [0, 0, 0]; // black stroke
      textDoc.strokeWidth = 2;
      textDoc.font = "Arial";
      textDoc.justification = ParagraphJustification.CENTER_JUSTIFY;
      textProp.setValue(textDoc);
      
      // Position at lower third
      textLayer.transform.position.setValue([COMP_W/2, COMP_H * 0.85]);
      
      // Fade in/out
      textLayer.opacity.setValueAtTime(textTimeline, 0);
      textLayer.opacity.setValueAtTime(textTimeline + 0.3, 100);
      textLayer.opacity.setValueAtTime(textTimeline + dur2 - 0.3, 100);
      textLayer.opacity.setValueAtTime(textTimeline + dur2, 0);
      
      // Move text layer to top
      textLayer.moveToBeginning();
    }
    textTimeline += (t < shotDurs.length) ? shotDurs[t] : 4;
  }

  // --- IMPORT LOGO FROM ASSETS ---
  var logoFiles = getFiles(assetsFolder, ["png","jpg","jpeg","svg"]);
  if(logoFiles.length > 0){
    var logoFootage = importFile(logoFiles[0]);
    var logoLayer = comp.layers.add(logoFootage);
    logoLayer.startTime = 0;
    logoLayer.outPoint = timeline;
    logoLayer.name = "Logo_Watermark";
    // Scale logo to ~8% of comp width
    var lw = logoFootage.width;
    if(lw > 0){
      var logoScale = (COMP_W * 0.08 / lw) * 100;
      logoLayer.transform.scale.setValue([logoScale, logoScale]);
    }
    // Position top-right corner with padding
    logoLayer.transform.position.setValue([COMP_W - 80, 60]);
    logoLayer.opacity.setValue(70);
    logoLayer.moveToBeginning();
  }

  // --- SET WORK AREA ---
  comp.workAreaStart = 0;
  comp.workAreaDuration = timeline;

  app.endUndoGroup();

  // --- SUMMARY ---
  var summary = "✅ Pipeline Assembly Complete!\n\n";
  summary += "Composition: " + COMP_NAME + "\n";
  summary += "Duration: " + timeline + "s @ " + COMP_FPS + "fps\n";
  summary += "Resolution: " + COMP_W + "x" + COMP_H + "\n\n";
  summary += "Layers created:\n";
  summary += "• " + Math.min(shotFiles.length, NUM_SHOTS) + " video shots (with cross dissolves)\n";
  summary += "• " + (voFiles.length > 0 ? "1" : "0") + " voice-over track\n";
  summary += "• " + (muFiles.length > 0 ? "1" : "0") + " music track (ducked -12dB)\n";
  summary += "• Text overlays on applicable shots\n";
  summary += "• " + (logoFiles.length > 0 ? "1 logo watermark" : "No logo found") + "\n\n";
  summary += "Next: Review timeline, adjust timing, add effects, render!";
  alert(summary);

})();
